version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    volumes:
      - ./configs:/configs
    networks:  # ← ДОБАВЬТЕ ЭТОТ БЛОК
      - microservices-net


networks:
  microservices-net:
    external: true 