version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "8000:8000"
      - "9091:9091"

    environment:
      METRICS_ADDR: ":9091"
      REDIS_ADDR: "redis:6379"
      RATELIMIT_PER_MIN: "600"
      RATELIMIT_BURST: "100"

    volumes:
      - ./configs:/configs
    networks:
      - microservices-net


networks:
  microservices-net:
    external: true 