version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "50051:50051"

    depends_on:
      postgres_auth:
        condition: service_healthy

    environment:
      DB_PASS: ${DB_PASS}
      DB_HOST: postgres_auth 
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: auth
      DB_SSLMODE: disable 

    volumes:
      - ./configs:/configs

    networks:
      - microservices-net  # ← ДОБАВЬТЕ ЭТУ СТРОКУ

    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:50051"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres_auth:
    image: postgres:15-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: auth

    ports:
      - "5433:5432"

    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
      
    networks:
      - microservices-net  

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_auth:

networks:
  microservices-net:
    external: true 