version: '3.8'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "50052:50052"

    depends_on:
      postgres_user:
        condition: service_healthy

    environment:
      DB_PASS: ${DB_PASS}
      DB_HOST: postgres_user
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: users
      DB_SSLMODE: disable 

    volumes:
      - ./configs:/configs

  postgres_user:
    image: postgres:15-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: users

    ports:
      - "5432:5435"

    volumes:
      - postgres_data_user:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_user:

networks:
  microservices-net:
    external: true 