version: '3.8'

services:
  company:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "50055:50055"

    depends_on:
      postgres_company:
        condition: service_healthy

    environment:
      DB_PASS: ${DB_PASS}
      DB_HOST: postgres_company
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: company
      DB_SSLMODE: disable 

    volumes:
      - ./configs:/configs

  postgres_company:
    image: postgres:15-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: company

    ports:
      - "5434:5432"

    volumes:
      - postgres_data_company:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_company:

networks:
  microservices-net:
    external: true 