-- Категории (из proto/skills/v1.SkillCategory):
--   1 = LANGUAGE, 2 = FRAMEWORK, 3 = DATABASE, 4 = INFRA,
--   5 = TOOL, 6 = CLOUD, 7 = DESIGN, 8 = OTHER

INSERT INTO skills (slug, name, category, popularity) VALUES
    -- LANGUAGE (1)
    ('go',           'Go',            1, 100),
    ('java',         'Java',          1, 100),
    ('python',       'Python',        1, 100),
    ('javascript',   'JavaScript',    1, 100),
    ('typescript',   'TypeScript',    1, 95),
    ('csharp',       'C#',            1, 80),
    ('cpp',          'C++',           1, 75),
    ('c',            'C',             1, 70),
    ('rust',         'Rust',          1, 70),
    ('kotlin',       'Kotlin',        1, 65),
    ('swift',        'Swift',         1, 50),
    ('php',          'PHP',           1, 60),
    ('ruby',         'Ruby',          1, 40),
    ('scala',        'Scala',         1, 30),
    ('dart',         'Dart',          1, 35),
    ('elixir',       'Elixir',        1, 20),
    ('haskell',      'Haskell',       1, 15),
    ('lua',          'Lua',           1, 15),
    ('r',            'R',             1, 25),
    ('matlab',       'MATLAB',        1, 20),
    ('bash',         'Bash',          1, 50),
    ('sql',          'SQL',           1, 90),
    ('html',         'HTML',          1, 90),
    ('css',          'CSS',           1, 90),
    ('sass',         'Sass/SCSS',     1, 50),
    ('solidity',     'Solidity',      1, 20),

    -- FRAMEWORK (2)
    ('react',           'React',           2, 100),
    ('vue',             'Vue.js',          2, 80),
    ('angular',         'Angular',         2, 75),
    ('svelte',          'Svelte',          2, 35),
    ('nextjs',          'Next.js',         2, 80),
    ('nuxt',            'Nuxt.js',         2, 35),
    ('redux',           'Redux',           2, 60),
    ('mobx',            'MobX',            2, 25),
    ('jquery',          'jQuery',          2, 30),
    ('tailwind',        'Tailwind CSS',    2, 70),
    ('bootstrap',       'Bootstrap',       2, 60),
    ('material-ui',     'Material UI',     2, 55),
    ('vite',            'Vite',            2, 60),
    ('webpack',         'Webpack',         2, 50),
    ('nodejs',          'Node.js',         2, 90),
    ('express',         'Express.js',      2, 70),
    ('nestjs',          'NestJS',          2, 50),
    ('spring',          'Spring',          2, 80),
    ('spring-boot',     'Spring Boot',     2, 80),
    ('hibernate',       'Hibernate',       2, 50),
    ('django',          'Django',          2, 65),
    ('flask',           'Flask',           2, 55),
    ('fastapi',         'FastAPI',         2, 60),
    ('rails',           'Ruby on Rails',   2, 30),
    ('laravel',         'Laravel',         2, 45),
    ('aspnet',          'ASP.NET',         2, 45),
    ('dotnet',          '.NET',            2, 60),
    ('fiber',           'Fiber',           2, 40),
    ('gin',             'Gin',             2, 45),
    ('echo',            'Echo',            2, 30),
    ('grpc-go',         'gRPC-Go',         2, 50),
    ('flutter',         'Flutter',         2, 40),
    ('react-native',    'React Native',    2, 45),
    ('electron',        'Electron',        2, 25),
    ('qt',              'Qt',              2, 25),
    ('tensorflow',      'TensorFlow',      2, 50),
    ('pytorch',         'PyTorch',         2, 55),
    ('pandas',          'pandas',          2, 60),
    ('numpy',           'NumPy',           2, 55),
    ('scikit-learn',    'scikit-learn',    2, 50),

    -- DATABASE (3)
    ('postgresql',   'PostgreSQL',    3, 100),
    ('mysql',        'MySQL',         3, 80),
    ('sqlite',       'SQLite',        3, 60),
    ('mssql',        'MS SQL Server', 3, 50),
    ('oracle',       'Oracle DB',     3, 40),
    ('mongodb',      'MongoDB',       3, 80),
    ('redis',        'Redis',         3, 80),
    ('elasticsearch','Elasticsearch', 3, 70),
    ('opensearch',   'OpenSearch',    3, 30),
    ('cassandra',    'Cassandra',     3, 35),
    ('clickhouse',   'ClickHouse',    3, 50),
    ('influxdb',     'InfluxDB',      3, 25),
    ('neo4j',        'Neo4j',         3, 25),
    ('dynamodb',     'DynamoDB',      3, 35),
    ('cockroachdb',  'CockroachDB',   3, 20),
    ('mariadb',      'MariaDB',       3, 35),
    ('couchdb',      'CouchDB',       3, 15),

    -- INFRA (4)
    ('docker',          'Docker',           4, 100),
    ('docker-compose',  'Docker Compose',   4, 85),
    ('kubernetes',      'Kubernetes',       4, 90),
    ('helm',            'Helm',             4, 50),
    ('linux',           'Linux',            4, 90),
    ('nginx',           'Nginx',            4, 75),
    ('haproxy',         'HAProxy',          4, 40),
    ('apache',          'Apache HTTPD',     4, 40),
    ('terraform',       'Terraform',        4, 60),
    ('ansible',         'Ansible',          4, 55),
    ('prometheus',      'Prometheus',       4, 60),
    ('grafana',         'Grafana',          4, 60),
    ('elk',             'ELK Stack',        4, 45),
    ('jaeger',          'Jaeger',           4, 30),
    ('opentelemetry',   'OpenTelemetry',    4, 40),
    ('istio',           'Istio',            4, 30),
    ('vault',           'HashiCorp Vault',  4, 30),
    ('consul',          'Consul',           4, 25),
    ('etcd',            'etcd',             4, 25),
    ('argocd',          'ArgoCD',           4, 40),

    -- TOOL (5)
    ('git',          'Git',           5, 100),
    ('github',       'GitHub',        5, 90),
    ('gitlab',       'GitLab',        5, 70),
    ('bitbucket',    'Bitbucket',     5, 35),
    ('jenkins',      'Jenkins',       5, 60),
    ('github-actions','GitHub Actions',5, 70),
    ('gitlab-ci',    'GitLab CI',     5, 55),
    ('teamcity',     'TeamCity',      5, 30),
    ('gradle',       'Gradle',        5, 50),
    ('maven',        'Maven',         5, 50),
    ('npm',          'npm',           5, 70),
    ('yarn',         'Yarn',          5, 55),
    ('pnpm',         'pnpm',          5, 35),
    ('grpc',         'gRPC',          5, 70),
    ('rest',         'REST API',      5, 95),
    ('graphql',      'GraphQL',       5, 55),
    ('protobuf',     'Protocol Buffers',5, 55),
    ('openapi',      'OpenAPI/Swagger',5, 65),
    ('postman',      'Postman',       5, 70),
    ('kafka',        'Apache Kafka',  5, 70),
    ('rabbitmq',     'RabbitMQ',      5, 65),
    ('nats',         'NATS',          5, 30),
    ('jira',         'Jira',          5, 70),
    ('confluence',   'Confluence',    5, 50),
    ('notion',       'Notion',        5, 40),
    ('vscode',       'VS Code',       5, 80),
    ('intellij',     'IntelliJ IDEA', 5, 70),
    ('goland',       'GoLand',        5, 50),
    ('pycharm',      'PyCharm',       5, 55),
    ('vim',          'Vim',           5, 40),
    ('selenium',     'Selenium',      5, 45),
    ('playwright',   'Playwright',    5, 35),
    ('jest',         'Jest',          5, 50),
    ('pytest',       'pytest',        5, 50),
    ('junit',        'JUnit',         5, 55),

    -- CLOUD (6)
    ('aws',          'AWS',           6, 80),
    ('gcp',          'Google Cloud',  6, 60),
    ('azure',        'Microsoft Azure',6, 65),
    ('yandex-cloud', 'Yandex Cloud',  6, 70),
    ('vk-cloud',     'VK Cloud',      6, 35),
    ('selectel',     'Selectel',      6, 35),
    ('digitalocean', 'DigitalOcean',  6, 35),
    ('cloudflare',   'Cloudflare',    6, 45),
    ('s3',           'AWS S3',        6, 60),
    ('lambda',       'AWS Lambda',    6, 45),
    ('ec2',          'AWS EC2',       6, 45),
    ('heroku',       'Heroku',        6, 25),
    ('vercel',       'Vercel',        6, 40),
    ('netlify',      'Netlify',       6, 30),
    ('minio',        'MinIO',         6, 45),

    -- DESIGN (7)
    ('figma',        'Figma',         7, 90),
    ('sketch',       'Sketch',        7, 30),
    ('adobe-xd',     'Adobe XD',      7, 30),
    ('photoshop',    'Photoshop',     7, 50),
    ('illustrator',  'Illustrator',   7, 35),
    ('ux',           'UX-дизайн',     7, 60),
    ('ui',           'UI-дизайн',     7, 65),

    -- OTHER (8)
    ('agile',         'Agile',                 8, 70),
    ('scrum',         'Scrum',                 8, 70),
    ('kanban',        'Kanban',                8, 50),
    ('english-b1',    'Английский B1+',        8, 80),
    ('english-b2',    'Английский B2+',        8, 60),
    ('english-c1',    'Английский C1+',        8, 30),
    ('algorithms',    'Алгоритмы и структуры', 8, 70),
    ('oop',           'ООП',                   8, 80),
    ('design-patterns','Паттерны проектирования',8, 60),
    ('clean-code',    'Чистый код',            8, 55),
    ('tdd',           'TDD',                   8, 35),
    ('ddd',           'DDD',                   8, 30),
    ('microservices', 'Микросервисы',          8, 70),
    ('event-driven',  'Event-driven',          8, 35);
